package cn.edu.cdtu.entity;
// default package
// Generated 2015-6-28 18:16:30 by Hibernate Tools 3.4.0.CR1

/**
 * TAdmin generated by hbm2java
 */
@SuppressWarnings("serial")
public class TAdmin implements java.io.Serializable {

	private String adminId;
	private String adminName;
	private String adminPassword;

	public TAdmin() {
	}

	public TAdmin(String adminId) {
		this.adminId = adminId;
	}

	public TAdmin(String adminId, String adminName, String adminPassword) {
		this.adminId = adminId;
		this.adminName = adminName;
		this.adminPassword = adminPassword;
	}

	public String getAdminId() {
		return this.adminId;
	}

	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	public String getAdminName() {
		return this.adminName;
	}

	public void setAdminName(String adminName) {
		this.adminName = adminName;
	}

	public String getAdminPassword() {
		return this.adminPassword;
	}

	public void setAdminPassword(String adminPassword) {
		this.adminPassword = adminPassword;
	}

}
