package cn.edu.cdtu.entity;
// default package
// Generated 2015-6-28 18:16:30 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TBook generated by hbm2java
 */
@SuppressWarnings("serial")
public class TBook implements java.io.Serializable {

	private String bookId;
	private TCategory TCategory;
	private String bookName;
	private String bookAuthor;
	private BigDecimal bookPrice;
	private BigDecimal bookCurrPrice;
	private BigDecimal bookDiscount;
	private String bookPress;
	private Integer bookPageNum;
	private Integer bookWordNum;
	private String bookPrinttime;
	private String bookPaper;
	private String bookKinds;
	private String bookImageB;
	private String bookImageS;
	private Integer bookOrderBy;
	private Set TOrderitems = new HashSet(0);
	private Set TCartitems = new HashSet(0);

	public TBook() {
	}

	public String getBookImageS() {
		return bookImageS;
	}

	public TBook(String bookId) {
		this.bookId = bookId;
	}

	public TBook(String bookId, TCategory TCategory, String bookName,
			String bookAuthor, BigDecimal bookPrice, BigDecimal bookCurrPrice,
			BigDecimal bookDiscount, String bookPress, Integer bookPageNum,
			Integer bookWordNum, String bookPrinttime, String bookPaper,
			String bookKinds, String bookImageB, String bookImageS,
			Integer bookOrderBy, Set TOrderitems, Set TCartitems) {
		this.bookId = bookId;
		this.TCategory = TCategory;
		this.bookName = bookName;
		this.bookAuthor = bookAuthor;
		this.bookPrice = bookPrice;
		this.bookCurrPrice = bookCurrPrice;
		this.bookDiscount = bookDiscount;
		this.bookPress = bookPress;
		this.bookPageNum = bookPageNum;
		this.bookWordNum = bookWordNum;
		this.bookPrinttime = bookPrinttime;
		this.bookPaper = bookPaper;
		this.bookKinds = bookKinds;
		this.bookImageB = bookImageB;
		this.bookImageS = bookImageS;
		this.bookOrderBy = bookOrderBy;
		this.TOrderitems = TOrderitems;
		this.TCartitems = TCartitems;
	}

	public String getBookId() {
		return this.bookId;
	}

	public void setBookId(String bookId) {
		this.bookId = bookId;
	}

	public TCategory getTCategory() {
		return this.TCategory;
	}

	public void setTCategory(TCategory TCategory) {
		this.TCategory = TCategory;
	}

	public String getBookName() {
		return this.bookName;
	}

	public void setBookName(String bookName) {
		this.bookName = bookName;
	}

	public String getBookAuthor() {
		return this.bookAuthor;
	}

	public void setBookAuthor(String bookAuthor) {
		this.bookAuthor = bookAuthor;
	}

	public BigDecimal getBookPrice() {
		return this.bookPrice;
	}

	public void setBookPrice(BigDecimal bookPrice) {
		this.bookPrice = bookPrice;
	}

	public BigDecimal getBookCurrPrice() {
		return this.bookCurrPrice;
	}

	public void setBookCurrPrice(BigDecimal bookCurrPrice) {
		this.bookCurrPrice = bookCurrPrice;
	}

	public BigDecimal getBookDiscount() {
		return this.bookDiscount;
	}

	public void setBookDiscount(BigDecimal bookDiscount) {
		this.bookDiscount = bookDiscount;
	}

	public String getBookPress() {
		return this.bookPress;
	}

	public void setBookPress(String bookPress) {
		this.bookPress = bookPress;
	}

	public Integer getBookPageNum() {
		return this.bookPageNum;
	}

	public void setBookPageNum(Integer bookPageNum) {
		this.bookPageNum = bookPageNum;
	}

	public Integer getBookWordNum() {
		return this.bookWordNum;
	}

	public void setBookWordNum(Integer bookWordNum) {
		this.bookWordNum = bookWordNum;
	}

	public String getBookPrinttime() {
		return this.bookPrinttime;
	}

	public void setBookPrinttime(String bookPrinttime) {
		this.bookPrinttime = bookPrinttime;
	}

	public String getBookPaper() {
		return this.bookPaper;
	}

	public void setBookPaper(String bookPaper) {
		this.bookPaper = bookPaper;
	}

	public String getBookKinds() {
		return this.bookKinds;
	}

	public void setBookKinds(String bookKinds) {
		this.bookKinds = bookKinds;
	}

	public String getBookImageB() {
		return this.bookImageB;
	}

	public void setBookImageB(String bookImageB) {
		this.bookImageB = bookImageB;
	}

	public String orderid() {
		return this.bookImageS;
	}

	public void setBookImageS(String bookImageS) {
		this.bookImageS = bookImageS;
	}

	public Integer getBookOrderBy() {
		return this.bookOrderBy;
	}

	public void setBookOrderBy(Integer bookOrderBy) {
		this.bookOrderBy = bookOrderBy;
	}

	public Set getTOrderitems() {
		return this.TOrderitems;
	}

	public void setTOrderitems(Set TOrderitems) {
		this.TOrderitems = TOrderitems;
	}

	public Set getTCartitems() {
		return this.TCartitems;
	}

	public void setTCartitems(Set TCartitems) {
		this.TCartitems = TCartitems;
	}

}
