package cn.edu.cdtu.entity;

import java.math.BigDecimal;

// default package
// Generated 2015-6-28 18:16:30 by Hibernate Tools 3.4.0.CR1

/**
 * TCartitem generated by hbm2java
 */
public class TCartitem implements java.io.Serializable {

	private String cartitemId;
	private TBook TBook;
	private TUser TUser;
	private Integer cartitemCount;
	private Integer cartitemOrderBy;

	// 添加小计方法
	public double getSubtotal() {
		/*
		 * 使用BigDecimal不会有误差 要求必须使用String类型构造器
		 */
		BigDecimal b1 = new BigDecimal(TBook.getBookCurrPrice() + "");
		BigDecimal b2 = new BigDecimal(cartitemCount + "");
		BigDecimal b3 = b1.multiply(b2);
		return b3.doubleValue();
	}

	public TCartitem() {
	}

	public TCartitem(String cartitemId) {
		this.cartitemId = cartitemId;
	}

	public TCartitem(String cartitemId, TBook TBook, TUser TUser,
			Integer cartitemCount, Integer cartitemOrderBy) {
		this.cartitemId = cartitemId;
		this.TBook = TBook;
		this.TUser = TUser;
		this.cartitemCount = cartitemCount;
		this.cartitemOrderBy = cartitemOrderBy;
	}

	public String getCartitemId() {
		return this.cartitemId;
	}

	public void setCartitemId(String cartitemId) {
		this.cartitemId = cartitemId;
	}

	public TBook getTBook() {
		return this.TBook;
	}

	public void setTBook(TBook TBook) {
		this.TBook = TBook;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public Integer getCartitemCount() {
		return this.cartitemCount;
	}

	public void setCartitemCount(Integer cartitemCount) {
		this.cartitemCount = cartitemCount;
	}

	public Integer getCartitemOrderBy() {
		return this.cartitemOrderBy;
	}

	public void setCartitemOrderBy(Integer cartitemOrderBy) {
		this.cartitemOrderBy = cartitemOrderBy;
	}

}
