package cn.edu.cdtu.entity;
// default package
// Generated 2015-6-28 18:16:30 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TCategory generated by hbm2java
 */
public class TCategory implements java.io.Serializable {

	private String categoryId;
	private TCategory TCategory;
	private String categoryName;
	private String categoryDesc;
	private Integer categoryOrderBy;
	private Set TBooks = new HashSet(0);
	private Set TCategories = new HashSet(0);
	List<TCategory> Category=new ArrayList<TCategory>();
	public Set getTBooks() {
		return TBooks;
	}

	public List<TCategory> getCategory() {
		return Category;
	}

	public void setCategory(List<TCategory> category) {
		Category = category;
	}

	public void setTBooks(Set tBooks) {
		TBooks = tBooks;
	}

	public Set getTCategories() {
		return TCategories;
	}

	public void setTCategories(Set tCategories) {
		TCategories = tCategories;
	}

	public TCategory() {
	}

	public TCategory(String categoryId) {
		this.categoryId = categoryId;
	}

	public TCategory(String categoryId, TCategory TCategory,
			String categoryName, String categoryDesc, Integer categoryOrderBy,
			Set TBooks, Set TCategories) {
		this.categoryId = categoryId;
		this.TCategory = TCategory;
		this.categoryName = categoryName;
		this.categoryDesc = categoryDesc;
		this.categoryOrderBy = categoryOrderBy;
		this.TBooks = TBooks;
		this.TCategories = TCategories;
	}

	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	public TCategory getTCategory() {
		return this.TCategory;
	}

	public void setTCategory(TCategory TCategory) {
		this.TCategory = TCategory;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getCategoryDesc() {
		return this.categoryDesc;
	}

	public void setCategoryDesc(String categoryDesc) {
		this.categoryDesc = categoryDesc;
	}

	public Integer getCategoryOrderBy() {
		return this.categoryOrderBy;
	}

	public void setCategoryOrderBy(Integer categoryOrderBy) {
		this.categoryOrderBy = categoryOrderBy;
	}



}
