package cn.edu.cdtu.entity;
// default package
// Generated 2015-6-28 18:16:30 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * TOrder generated by hbm2java
 */
public class TOrder implements java.io.Serializable {

	private String orderId;
	private TUser TUser;
	private String orderTime;
	private BigDecimal orderTotal;
	private Integer orderStatus;
	private String orderAddress;
	private Set TOrderitems = new HashSet(0);

	
	private List<TOrderitem> orderItemList;
	public List<TOrderitem> getOrderItemList() {
		return orderItemList;
	}

	public void setOrderItemList(List<TOrderitem> orderItemList) {
		this.orderItemList = orderItemList;
	}

	public TOrder() {
	}

	public TOrder(String orderId) {
		this.orderId = orderId;
	}

	public TOrder(String orderId, TUser TUser, String orderTime,
			BigDecimal orderTotal, Integer orderStatus, String orderAddress,
			Set TOrderitems) {
		this.orderId = orderId;
		this.TUser = TUser;
		this.orderTime = orderTime;
		this.orderTotal = orderTotal;
		this.orderStatus = orderStatus;
		this.orderAddress = orderAddress;
		this.TOrderitems = TOrderitems;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public String getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(String orderTime) {
		this.orderTime = orderTime;
	}

	public BigDecimal getOrderTotal() {
		return this.orderTotal;
	}

	public void setOrderTotal(BigDecimal orderTotal) {
		this.orderTotal = orderTotal;
	}

	public Integer getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(Integer orderStatus) {
		this.orderStatus = orderStatus;
	}

	public String getOrderAddress() {
		return this.orderAddress;
	}

	public void setOrderAddress(String orderAddress) {
		this.orderAddress = orderAddress;
	}

	public Set getTOrderitems() {
		return this.TOrderitems;
	}

	public void setTOrderitems(Set TOrderitems) {
		this.TOrderitems = TOrderitems;
	}

}
